### PR TITLE
Cleanup code.

### PR DESCRIPTION
**Pull request by DelxHQ**
This PR makes it easier for other developers to read the code. (Not to bash on your style)

### CODE REVIEW

**Comment by buchwasa** [comment]
I would argue that this pull request makes 0 difference on who is going to contribute at it's present time

**Comment by bwdotdev** [comment]
> I would argue that this pull request makes 0 difference on who is going to contribute at it's present time

I would argue that the most important thing when writing code is readability. If code is not readable then it puts people off contributing and very often leads to an increase in bugs. I would also argue that you being entitled and making people feel like their contributions aren't helpful is extremely unhelpful if you want people to contribute more.

**Comment by buchwasa** [comment]
Thank you bradw, very cool!

**Comment by lukeeey** [comment]
I agree some of it looks better in this PR but you didn’t need to change all of it.

That being said, renaming the methods prefixed with underscore seems fine. That convention is for JavaScript to identifier internal methods, but TS has an explicit private keyword.

**Comment by daniktheboss** [comment]
I agree with bradw, buchwasa you are acting very entitled.

**Comment by lukeeey** [comment]
> I agree with bradw, buchwasa you are acting very entitled.

it doesn’t really do anything tho

**Comment by bwdotdev** [comment]
I also agree with bradw.

**Comment by DelxHQ** [comment]
I thirdly agree with bradw.

**Comment by lukeeey** [comment]
well, i mean, bradw is a cool guy

**Comment by sn3akrr** [comment]
he is a cool guy, i can confirm

**Pull request merged**
